export enum TransactionStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  ESCROW_FUNDED = 'ESCROW_FUNDED',
  BLOCKCHAIN_SUBMITTED = 'BLOCKCHAIN_SUBMITTED',
  CONFIRMING = 'CONFIRMING',
  CONFIRMED = 'CONFIRMED',
  DISPUTED = 'DISPUTED',
  REFUNDED = 'REFUNDED',
}
